### PR TITLE
M140 S0 (Bed cooldown) integration into Custom G-code End Commands

### PR DESCRIPTION
**Pull request by blue-ice**
The change that I made in this pull request is to set "turn off the bed once the print is done" (M140 S0) into the default Slic3r Custom G-code End Commands.

When printing, I find it helpful to shut off the bed once the print is done, so that the parts can be removed. I added this command into my setup of Slic3r and find it useful, which is why I think it should be a default command.

Comments and thoughts appreciated.

blue-ice

### CODE REVIEW

**Comment by strahlex** [comment]
The M104 code does not work for all firmwares. I think this should be made firmware independent.

**Comment by blue-ice** [comment]
What are the alternative commands for the other firmwares?

**Comment by strahlex** [comment]
See GCodeOutput.cpp

**Comment by strahlex** [comment]
It would be nice if we would have GCode flavour specific default begin and end GCode commands.

**Comment by lordofhyphens** [comment]
There's too many different printers and firmware that slic3r has to support for this to be particularly useful. Even for ones with similar dialects they often behave differently, like M190, etc. 

Better to just put the defaults in a config and let the user set them up right for their printer.
I think this PR should be closed.

**Comment by 7eggert** [comment]
So if M140 is the most common command and assuming it does not harm other devices, you could write

; uncomment the correct line:
; M140 S0; Turn headbed off on most devices
; M0815 S0; Turn headbed off on $that_other_device

**Comment by lordofhyphens** [comment]
Implemented as d8a743d (end gcode now acts like start gcode).

**Pull request closed without merging**
