### PR TITLE
Added jetting fill pattern 

### PR DESCRIPTION
**Pull request by rockandsalt**
let me know if I need to create some unit test.

### CODE REVIEW

**Comment by rockandsalt** [comment]
it's a new fill pattern we use in the lab I work in. We use it for an ink jet printer. Here's an example
## Rectilinear 
rectilinear 
## vs 
## Jetting
jetting

**Comment by lordofhyphens** [comment]
Would appreciate a unit test.

**Comment by rockandsalt** [comment]
@lordofhyphens, the fill patterns don't have unit test and the classes are not defined in the xsp files. Do you still require the unit test?

**Comment by rockandsalt** [comment]
never mind, found the test

**Comment by lordofhyphens** [comment]
How does this compare to Grid infill?

**Comment by lordofhyphens** [comment]
@rockandsalt there a specific reason you closed your PR?

**Comment by rockandsalt** [comment]
@lordofhyphens, the PR was old and was really busy for the last 4 month. I will reopen it when I have time to write the unit test required to merge into master branch. Or if there's demand for this fill pattern. 

For your previous question, the only difference with the grid pattern is that the line inside are all single line.

**Pull request closed without merging**
