### PR TITLE
calculation of COG in Slic3r

### PR DESCRIPTION
**Pull request by roman-dvorak**
Hi, I have prepared edits that calculates COG (center of gravity) based on filament extrusion. Output of that COG is in gcode as a comment

### CODE REVIEW

**Comment by ledvinap** [comment]
@roman-dvorak:
- changing whitespace makes this PR unreadable, IMO nobody is going to review it
- COG calculation can be quite easily done as postprocessing step, without modifying slic3r code (maybe some hints may be added to gcode)

**Comment by lordofhyphens** [comment]
Put all of the whitespace-only changes back--put those in a separate PR.

**Comment by roman-dvorak** [comment]
Thank you for answers. 

> Revert all changes that are only to whitespace.

Whitespaces were reverted from this PR. I'll make new one. 

> COG calculation can be quite easily done as postprocessing step, without modifying slic3r code (maybe some hints may be added to gcode)

Yes and no.. :) ... COG calculation from Gcode is quite easy. I made python script for that. But if you are using a printer that doesn't support retraction code. Retraction code is same as extrusion. And retraction is done at some coordinates and extrusion (after retraction) is done at another place. And if you print for example cylinder, there is a systematic error. Retraction place is "lighter" then opposite part of the model. 

Yes, retraction is easily detectable (it is negative value) but detect extrusion after retraction is more difficult. 

And there is another related thing. (And maybe you can help me). This COG is in the printer's coordinates. I need to get the offset model when importing. But it will be within the next PR

**Comment by roman-dvorak** [comment]
> Needs tests

Is there any general procedure for testing this? Can I help you with that?

**Comment by lordofhyphens** [comment]
Re:tests what am looking for is basic "this code does what I expect it to" tests.

**Comment by roman-dvorak** [comment]
Ok. I'll try to prepare some test models. Probably tomorow.

**Comment by roman-dvorak** [comment]
Some tests:

**Test 1**
Model:
Cube 20x20x20 in origin of coordinates
Snímek z 2020-05-14 23-48-40

Slicing:
`
./slic3r.pl --dont-arrange ~/slic3r_test/test1.stl 
`

From gcode:
```
; cog_x = 10.005586
; cog_y = 10.005532
; cog_z = 10.228147
```

**Test 2**
Cube from 1st test translated to 90, 90, 0. Expected COG in 100, 100, 10. 

Output:
```
; cog_x = 99.994804
; cog_y = 99.994795
; cog_z = 10.228147
```

**Test 3**
Cube in the air. Cube (20x20x20) from Test 1 translated to 0, 0, 20.
Snímek z 2020-05-14 23-54-20

Output:
```
; cog_x = 10.005586
; cog_y = 10.005532
; cog_z = 10.228147
```
Model was translated back to min_z = 0.0. Therefore this result is right. 

**Test 4**
Snímek z 2020-05-14 23-59-20

```
; cog_x = -28.193727
; cog_y = 27.185008
; cog_z = 18.274891
```
This can be right. Automatical centering was disabled.

With enabled centring:
```
; cog_x = 103.265931
; cog_y = 92.215823
; cog_z = 18.274891
```

**Comment by roman-dvorak** [comment]
I'm not sure why some travis/build tests are failing. But I guess it's not my error, because it's been there a longer time.

**Comment by lordofhyphens** [comment]
What I'd like to see is a few tests to check the expectations of your code under https://github.com/slic3r/Slic3r/tree/master/src/test/libslic3r

**Comment by roman-dvorak** [comment]
@lordofhyphens Is a test that check exists of `cog_x|y|z` values in gcode enough?

**Comment by lordofhyphens** [comment]
Yes, as that's what the code is supposed to do :)

**Comment by roman-dvorak** [comment]
@lordofhyphens Hi, I have created tests that:
 * Check if cog_x, y, z parameters are in gcode
 * Check if the value of cog is correct. 

So, i think that it is ok. My COG tests are passing.

**Comment by lordofhyphens** [comment]
Accepting; test failures have been fixed in master.

**Comment by lordofhyphens** [comment]
@roman-dvorak Thanks!

**Pull request merged**
