### PR TITLE
Used filament outputs (gcode comments) in more computer-parseable format

### PR DESCRIPTION
**Pull request by roman-dvorak**
Hi, currently `filament used` comments in gcode are not well parseable. Because they contain space in the name. And multiple values in the value part of the parameter. And there is more parameters with the same name and different value type (mass/length/volume). 

```
; filament used = 4361.4mm (10.5cm3)
; filament used = 13.0g
; total filament cost = 0.0
```

I have edited these outputs to more processable format.

### CODE REVIEW

**Comment by lordofhyphens** [comment]
@roman-dvorak please rebase this onto master and fix merge conflicts.

**Comment by roman-dvorak** [comment]
> @roman-dvorak please rebase this onto master and fix merge conflicts.

@lordofhyphens Sorry for my late answer. It should be mergeable now, 

With accepting of this PR, I have prepared a script for google sheets (tables) which is able to show mass/filament length from gcode link directly in the table as a number. 

Snímek z 2020-06-19 14-01-31

**Comment by lordofhyphens** [comment]
@roman-dvorak yes, but please add some output  tests when you do so.

**Comment by roman-dvorak** [comment]
> @roman-dvorak yes, but please add some output tests when you do so.

@lordofhyphens Thank you for merging. Yes, I will add the tests as soon as possible in next PR.

**Pull request merged**
