### PR TITLE
Patch for #4620 - ensure posDetectSurfaces is invalidated on slice change

### LINKED ISSUE #4620: Top and bottom solid layers vanish when changed
**Describe the bug**
Whenever I change the number of top or bottom solid layers, either through retyping or up/down arrows, all existing top and bottom solid layers vanish.  Independent of tab/dialog setting.  Independent of background processing.

**To Reproduce**
Load any model.  A test cube will do.  Use a config that has top and bottom layers. 
Change the number of top layers.
See the top/bottom layers vanish

[missing-tb-layers.zip](https://github.com/slic3r/Slic3r/files/2622904/missing-tb-layers.zip)

**Expected behavior**
Number of top and bottom layers should match config

**Screenshots**
missing-tb-layers

**Desktop (please complete the following information):**
 - OS: Fedora 26 x86-64
 - Version: git 33b3faacfd3b50cc643d6eecd6f48aec8ddcc7bc

### PR DESCRIPTION
**Pull request by lordofhyphens**
Invalidate posDetectSurfaces during make_perimeters() when posSlice would also get invalidated.
Can't use invalidate_step() as that invalidates the perimeters as well.

Fixes #4620

### CODE REVIEW

**Comment by lordofhyphens** [comment]
Also have a regression test added to the CATCH test suite.

**Comment by VanessaE** [comment]
I can't comment on the code itself, but the behavior is spot-on.  lgtm.

**Comment by alranel** [comment]
I'd turn `this->state.invalidate(posSlice);` into `this->invalidate_step(posSlice);` like we were doing before the bisected commit. In order to do this safely, I'd move set_started(posPerimeters) after the "if (this->typed_slices) {" block.
I think that state.invalidate() should be never called directly, except from invalidate_step() which ensures dependencies are invalidated too

**Comment by lordofhyphens** [comment]
Done.

**Pull request merged**
